dbutils.fs.mkdirs("/ayush/")
dbutils.fs.put("/ayush/input.txt", "Hello, World! This is a test file data. Hello, Using this for word count.")
display(dbutils.fs.ls("dbfs:/ayush/"))
val textFile = sc.textFile("dbfs:/ayush/input.txt")
val counts = textFile.flatMap(line => line.split(" "))
                 .map(word => (word, 1))
                 .reduceByKey(_ + _)
counts.saveAsTextFile("dbfs:/ayush/wordcount")
dbutils.fs.head("dbfs:/ayush/wordcount/part-00000",70)